- hosts: master
  become_user: renantf
  tasks:

    - name: download istio script
      get_url:
        url: https://istio.io/downloadIstio
        dest: /users/renantf/downloadIstioCandidate.sh
        mode: a+x
      register: istio_script
    
    - name: run istio download script
      shell: ISTIO_VERSION={{ istio_version }} sh "{{ istio_script.dest }}"

    - name: remove istio download script
      file:
        path: "{{ istio_script.dest }}"
        state: absent

    - name: append istio binaries path in PATH
      lineinfile:
        dest: $HOME/.tcshrc
        line: setenv PATH ${PATH}:${HOME}/istio-{{ istio_version }}/bin
        state: present
        regexp: setenv PATH \$\{PATH\}:\$\{HOME\}/istio-{{ istio_version }}/bin
        create: yes
